PACKAGE = rescore

SOURCE  = \
	Yacht.java \
	YachtClass.java \
	YachtManager.java \
	Main.java \
	NamedEntity.java \
	Regatta.java \
	Group.java \
	Leg.java \

RMI_SOURCE =

MAIN       = Main

include $(JAVA_DEV_ROOT)/Makefile
